### ISSUE TITLE
[cloud-vision-python]:

### ISSUE THREAD

**Issue by bbiesele** [googlecodelabs/feedback#1040]
On MacOS BigSur 11.6 (20G165), Mac mini (M1, 2020) 16 GB

Issue installing per instructions on https://codelabs.developers.google.com/codelabs/cloud-vision-api-python/#5

william@mini21 Vision %  pip3 freeze | grep google-cloud-vision
Error processing line 1 of /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vision-1.0.0-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 170, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
google-cloud-vision==2.6.2
william@mini21 Vision % 

then:
william@mini21 Vision % python3 -c "import google.cloud.vision"
Error processing line 1 of /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vision-1.0.0-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 170, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored

**Comment by PicardParis** [comment]
Hi @bbiesele,
- It looks like an issue with your Python system environment.
- I'd recommend to check the following [Setting up a Python development environment](https://cloud.google.com/python/docs/setup) and use `venv` to develop in a clean isolated environment.
- Closing this issue. Feel free to reopen if needed.
