### ISSUE TITLE
[cloud-app-engine-python3] 

### ISSUE THREAD

**Issue by jamiesonpepper** [googlecodelabs/feedback#1081]
Tested this today and I get a 502 Bad Gateway response from nginx. Looked at the logs from AppEngine and there is an exception being thrown in gunicorn on startup and the most important part of the traceback is the "cannot import name 'json' from 'itsdangerous'" entry near the end of the stack:

2022-02-19 22:40:35 default[20220219t223928]  [2022-02-19 22:40:35 +0000] [10] [INFO] Starting gunicorn 20.1.0
2022-02-19 22:40:35 default[20220219t223928]  [2022-02-19 22:40:35 +0000] [10] [INFO] Listening at: http://0.0.0.0:8081 (10)
2022-02-19 22:40:35 default[20220219t223928]  [2022-02-19 22:40:35 +0000] [10] [INFO] Using worker: gthread
2022-02-19 22:40:35 default[20220219t223928]  [2022-02-19 22:40:35 +0000] [20] [INFO] Booting worker with pid: 20
2022-02-19 22:40:35 default[20220219t223928]  [2022-02-19 22:40:35 +0000] [23] [INFO] Booting worker with pid: 23
2022-02-19 22:40:35 default[20220219t223928]  [2022-02-19 22:40:35 +0000] [20] [ERROR] Exception in worker process
2022-02-19 22:40:35 default[20220219t223928]  Traceback (most recent call last):    File "/layers/google.python.pip/pip/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker      worker.init_process()    File "/layers/google.python.pip/pip/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 92, in init_process      super().init_process()    File "/layers/google.python.pip/pip/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process      self.load_wsgi()    File "/layers/google.python.pip/pip/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi      self.wsgi = self.app.wsgi()    File "/layers/google.python.pip/pip/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi      self.callable = self.load()    File "/layers/google.python.pip/pip/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load      return self.load_wsgiapp()    File "/layers/google.python.pip/pip/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp      return util.import_app(self.app_uri)    File "/layers/google.python.pip/pip/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app      mod = importlib.import_module(module)    File "/opt/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module      return _bootstrap._gcd_import(name[level:], package, level)    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load    File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked    File "<frozen importlib._bootstrap_external>", line 850, in exec_module    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed    File "/srv/main.py", line 1, in <module>      import flask    File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/__init__.py", line 19, in <module>      from . import json    File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/json/__init__.py", line 15, in <module>      from itsdangerous import json as _json  ImportError: cannot import name 'json' from 'itsdangerous' (/layers/google.python.pip/pip/lib/python3.9/site-packages/itsdangerous/__init__.py)
2022-02-19 22:40:35 default[20220219t223928]  [2022-02-19 22:40:35 +0000] [20] [INFO] Worker exiting (pid: 20)

Resolution:

I fixed this by changing Flask to use 1.1.4 in my requirements.txt to get rid of the error above, but then ran into the other issue from the link below with markupsafe and had to add markupsafe==2.0.1 in my requirements.txt.

References:
https://github.com/aws/aws-sam-cli/issues/3661
https://serverfault.com/questions/1094062/from-itsdangerous-import-json-as-json-importerror-cannot-import-name-json-fr

**Comment by PicardParis** [comment]
Thanks a lot for reporting the issue. I'll make an update pass asap.

**Comment by PicardParis** [comment]
- [x] Update codelab with latest Flask version
- [x] Test codelab
- [x] Publish updated codelab

**Comment by PicardParis** [comment]
- ✔️ The codelab has been updated:
  - Now uses Flask's latest version (2.0.3)
  - Decorators have been changed to use the more simple form `@app.get("/")`
  - https://codelabs.developers.google.com/codelabs/cloud-app-engine-python3
- 🙏 Thanks again for taking the time to report the issue.
