### ISSUE TITLE
[cloud-run-django]: gcloud builds submit --config migrate.yaml

### ISSUE THREAD

**Issue by cedenoaugusto** [googlecodelabs/feedback#1156]
After I ran following command: 
gcloud builds submit --config migrate.yaml

I got this error:

```
Creating temporary tarball archive of 13 file(s) totalling 9.0 KiB before compression.
Uploading tarball of [.] to [gs://lab-augusto_cloudbuild/source/1665601615.073318-e0795d28def54e48b4702ed3df33ff06.tgz]
Created [https://cloudbuild.googleapis.com/v1/projects/lab-augusto/locations/global/builds/7f6f5fc9-391e-47ca-ada3-cdea7fdb82ea].
Logs are available at [ https://console.cloud.google.com/cloud-build/builds/7f6f5fc9-391e-47ca-ada3-cdea7fdb82ea?project=529236996508 ].
REMOTE BUILD OUTPUT
starting build "7f6f5fc9-391e-47ca-ada3-cdea7fdb82ea"

FETCHSOURCE
Fetching storage object: gs://lab-augusto_cloudbuild/source/1665601615.073318-e0795d28def54e48b4702ed3df33ff06.tgz#1665601615274318
Copying gs://lab-augusto_cloudbuild/source/1665601615.073318-e0795d28def54e48b4702ed3df33ff06.tgz#1665601615274318...
/ [1 files][  4.3 KiB/  4.3 KiB]
Operation completed over 1 objects/4.3 KiB.
BUILD
Starting Step #0 - "docker-layer"
Step #0 - "docker-layer": Already have image (with digest): gcr.io/cloud-builders/docker
Step #0 - "docker-layer": Sending build context to Docker daemon   21.5kB
Step #0 - "docker-layer": Step 1/2 : FROM gcr.io/lab-augusto/myimage
Step #0 - "docker-layer": latest: Pulling from lab-augusto/myimage
Step #0 - "docker-layer": 53e5e158da5a: Already exists
Step #0 - "docker-layer": 082ae7677522: Already exists
Step #0 - "docker-layer": 3c2cba919283: Already exists
Step #0 - "docker-layer": bc56bf61067d: Pulling fs layer
Step #0 - "docker-layer": 52f6599165e3: Pulling fs layer
Step #0 - "docker-layer": c00c1af1f21c: Pulling fs layer
Step #0 - "docker-layer": a7ba0e068e12: Pulling fs layer
Step #0 - "docker-layer": 5fe8cae7a9fe: Pulling fs layer
Step #0 - "docker-layer": 93440c16f076: Pulling fs layer
Step #0 - "docker-layer": 7d245ed901e3: Pulling fs layer
Step #0 - "docker-layer": 352df61c565b: Pulling fs layer
Step #0 - "docker-layer": 448e99dda5d1: Pulling fs layer
Step #0 - "docker-layer": 70636c777983: Pulling fs layer
Step #0 - "docker-layer": 854d5d0cac45: Pulling fs layer
Step #0 - "docker-layer": 7e132b325448: Pulling fs layer
Step #0 - "docker-layer": 95b5e8f4dd11: Pulling fs layer
Step #0 - "docker-layer": 308f029891ca: Pulling fs layer
Step #0 - "docker-layer": 9e1b79ed05fb: Pulling fs layer
Step #0 - "docker-layer": a7ba0e068e12: Waiting
Step #0 - "docker-layer": 5fe8cae7a9fe: Waiting
Step #0 - "docker-layer": 93440c16f076: Waiting
Step #0 - "docker-layer": 7d245ed901e3: Waiting
Step #0 - "docker-layer": 352df61c565b: Waiting
Step #0 - "docker-layer": 448e99dda5d1: Waiting
Step #0 - "docker-layer": 70636c777983: Waiting
Step #0 - "docker-layer": 854d5d0cac45: Waiting
Step #0 - "docker-layer": 7e132b325448: Waiting
Step #0 - "docker-layer": 95b5e8f4dd11: Waiting
Step #0 - "docker-layer": 308f029891ca: Waiting
Step #0 - "docker-layer": 9e1b79ed05fb: Waiting
Step #0 - "docker-layer": 52f6599165e3: Verifying Checksum
Step #0 - "docker-layer": 52f6599165e3: Download complete
Step #0 - "docker-layer": c00c1af1f21c: Download complete
Step #0 - "docker-layer": 5fe8cae7a9fe: Verifying Checksum
Step #0 - "docker-layer": 5fe8cae7a9fe: Download complete
Step #0 - "docker-layer": a7ba0e068e12: Verifying Checksum
Step #0 - "docker-layer": a7ba0e068e12: Download complete
Step #0 - "docker-layer": 7d245ed901e3: Verifying Checksum
Step #0 - "docker-layer": 7d245ed901e3: Download complete
Step #0 - "docker-layer": 93440c16f076: Verifying Checksum
Step #0 - "docker-layer": 93440c16f076: Download complete
Step #0 - "docker-layer": 352df61c565b: Verifying Checksum
Step #0 - "docker-layer": 352df61c565b: Download complete
Step #0 - "docker-layer": 448e99dda5d1: Verifying Checksum
Step #0 - "docker-layer": 448e99dda5d1: Download complete
Step #0 - "docker-layer": bc56bf61067d: Verifying Checksum
Step #0 - "docker-layer": bc56bf61067d: Download complete
Step #0 - "docker-layer": 7e132b325448: Verifying Checksum
Step #0 - "docker-layer": 7e132b325448: Download complete
Step #0 - "docker-layer": 854d5d0cac45: Verifying Checksum
Step #0 - "docker-layer": 854d5d0cac45: Download complete
Step #0 - "docker-layer": 95b5e8f4dd11: Verifying Checksum
Step #0 - "docker-layer": 95b5e8f4dd11: Download complete
Step #0 - "docker-layer": 9e1b79ed05fb: Verifying Checksum
Step #0 - "docker-layer": 9e1b79ed05fb: Download complete
Step #0 - "docker-layer": 308f029891ca: Verifying Checksum
Step #0 - "docker-layer": 308f029891ca: Download complete
Step #0 - "docker-layer": 70636c777983: Verifying Checksum
Step #0 - "docker-layer": 70636c777983: Download complete
Step #0 - "docker-layer": bc56bf61067d: Pull complete
Step #0 - "docker-layer": 52f6599165e3: Pull complete
Step #0 - "docker-layer": c00c1af1f21c: Pull complete
Step #0 - "docker-layer": a7ba0e068e12: Pull complete
Step #0 - "docker-layer": 5fe8cae7a9fe: Pull complete
Step #0 - "docker-layer": 93440c16f076: Pull complete
Step #0 - "docker-layer": 7d245ed901e3: Pull complete
Step #0 - "docker-layer": 352df61c565b: Pull complete
Step #0 - "docker-layer": 448e99dda5d1: Pull complete
Step #0 - "docker-layer": 70636c777983: Pull complete
Step #0 - "docker-layer": 854d5d0cac45: Pull complete
Step #0 - "docker-layer": 7e132b325448: Pull complete
Step #0 - "docker-layer": 95b5e8f4dd11: Pull complete
Step #0 - "docker-layer": 308f029891ca: Pull complete
Step #0 - "docker-layer": 9e1b79ed05fb: Pull complete
Step #0 - "docker-layer": Digest: sha256:1d1136e7156fc7839e669dd63556ed8ed9aa5cfdfec1a76731bc16fb51095e6f
Step #0 - "docker-layer": Status: Downloaded newer image for gcr.io/lab-augusto/myimage:latest
Step #0 - "docker-layer":  c2b7cf099ea0
Step #0 - "docker-layer": Step 2/2 : COPY --from=gcr.io/cloudsql-docker/gce-proxy /cloud_sql_proxy /cloudsql/cloud_sql_proxy
Step #0 - "docker-layer": latest: Pulling from cloudsql-docker/gce-proxy
Step #0 - "docker-layer": 0a602d5f6ca3: Pulling fs layer
Step #0 - "docker-layer": efe76ef81f3a: Pulling fs layer
Step #0 - "docker-layer": 0a602d5f6ca3: Verifying Checksum
Step #0 - "docker-layer": 0a602d5f6ca3: Download complete
Step #0 - "docker-layer": efe76ef81f3a: Verifying Checksum
Step #0 - "docker-layer": efe76ef81f3a: Download complete
Step #0 - "docker-layer": 0a602d5f6ca3: Pull complete
Step #0 - "docker-layer": efe76ef81f3a: Pull complete
Step #0 - "docker-layer": Digest: sha256:1acfbb717e8846f8e9f376b44a33899d64c15988aee229bff5e8dec50a796c6e
Step #0 - "docker-layer": Status: Downloaded newer image for gcr.io/cloudsql-docker/gce-proxy:latest
Step #0 - "docker-layer":  7bb6c41959b5
Step #0 - "docker-layer": Successfully built 7bb6c41959b5
Step #0 - "docker-layer": Successfully tagged gcr.io/lab-augusto/myimage-proxy:latest
Finished Step #0 - "docker-layer"
Starting Step #1 - "migrate"
Step #1 - "migrate": Already have image: gcr.io/lab-augusto/myimage-proxy
Step #1 - "migrate": 2022/10/12 19:07:23 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
Step #1 - "migrate": 2022/10/12 19:07:23 errors parsing config:
Step #1 - "migrate":    googleapi: Error 403: The client is not authorized to make this request., notAuthorized
Step #1 - "migrate": Traceback (most recent call last):
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
Step #1 - "migrate":     self.connect()
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
Step #1 - "migrate":     return func(*args, **kwargs)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
Step #1 - "migrate":     self.connection = self.get_new_connection(conn_params)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
Step #1 - "migrate":     return func(*args, **kwargs)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
Step #1 - "migrate":     connection = Database.connect(**conn_params)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
Step #1 - "migrate":     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Step #1 - "migrate": psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
Step #1 - "migrate":    Is the server running on that host and accepting TCP/IP connections?
Step #1 - "migrate":
Step #1 - "migrate":
Step #1 - "migrate": The above exception was the direct cause of the following exception:
Step #1 - "migrate":
Step #1 - "migrate": Traceback (most recent call last):
Step #1 - "migrate":   File "/workspace/manage.py", line 22, in <module>
Step #1 - "migrate":     main()
Step #1 - "migrate":   File "/workspace/manage.py", line 18, in main
Step #1 - "migrate":     execute_from_command_line(sys.argv)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
Step #1 - "migrate":     utility.execute()
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
Step #1 - "migrate":     self.fetch_command(subcommand).run_from_argv(self.argv)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
Step #1 - "migrate":     self.execute(*args, **cmd_options)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
Step #1 - "migrate":     output = self.handle(*args, **options)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
Step #1 - "migrate":     res = handle_func(*args, **kwargs)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 114, in handle
Step #1 - "migrate":     executor = MigrationExecutor(connection, self.migration_progress_callback)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
Step #1 - "migrate":     self.loader = MigrationLoader(self.connection)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
Step #1 - "migrate":     self.build_graph()
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/migrations/loader.py", line 235, in build_graph
Step #1 - "migrate":     self.applied_migrations = recorder.applied_migrations()
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
Step #1 - "migrate":     if self.has_table():
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 57, in has_table
Step #1 - "migrate":     with self.connection.cursor() as cursor:
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
Step #1 - "migrate":     return func(*args, **kwargs)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/backends/base/base.py", line 323, in cursor
Step #1 - "migrate":     return self._cursor()
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/backends/base/base.py", line 299, in _cursor
Step #1 - "migrate":     self.ensure_connection()
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
Step #1 - "migrate":     return func(*args, **kwargs)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
Step #1 - "migrate":     with self.wrap_database_errors:
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
Step #1 - "migrate":     raise dj_exc_value.with_traceback(traceback) from exc_value
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
Step #1 - "migrate":     self.connect()
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
Step #1 - "migrate":     return func(*args, **kwargs)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
Step #1 - "migrate":     self.connection = self.get_new_connection(conn_params)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
Step #1 - "migrate":     return func(*args, **kwargs)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
Step #1 - "migrate":     connection = Database.connect(**conn_params)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
Step #1 - "migrate":     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Step #1 - "migrate": django.db.utils.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
Step #1 - "migrate":    Is the server running on that host and accepting TCP/IP connections?
Step #1 - "migrate":
Finished Step #1 - "migrate"
ERROR
ERROR: build step 1 "gcr.io/lab-augusto/myimage-proxy" failed: step exited with non-zero status: 1


BUILD FAILURE: Build step failure: build step 1 "gcr.io/lab-augusto/myimage-proxy" failed: step exited with non-zero status: 1
ERROR: (gcloud.builds.submit) build 7f6f5fc9-391e-47ca-ada3-cdea7fdb82ea completed with status "FAILURE"
```

**Comment by glasnt** [comment]
The issue you're having is around database connectivity. Can you confirm you have the `DATABASE_URL` configured and stored in Secret Manager (the second half of step 5)
