### ISSUE TITLE
[cloud-run-wagtail]: Step #1 - "migrate": : ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>)

### ISSUE THREAD

**Issue by KingBain** [googlecodelabs/feedback#1231]
No longer able to follow tutorial. 

unable to get past Section 7
![image](https://github.com/googlecodelabs/feedback/assets/367922/3dfc90f8-46e4-48c1-b8e1-aa0b7267375f)

Output from terminal 
```
Step #0 - "docker-layer": Successfully built def5345c1bfe
Step #0 - "docker-layer": Successfully tagged gcr.io/phx-01h1yptgmche7jcy01wzzpw2rf/myimage-proxy:latest
Finished Step #0 - "docker-layer"
Starting Step #1 - "migrate"
Step #1 - "migrate": Already have image: gcr.io/phx-01h1yptgmche7jcy01wzzpw2rf/myimage-proxy
Step #1 - "migrate": 2023/06/05 15:14:35 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
Step #1 - "migrate": 2023/06/05 15:14:35 Listening on 127.0.0.1:5432 for phx-01h1yptgmche7jcy01wzzpw2rf:us-central1:myinstance
Step #1 - "migrate": 2023/06/05 15:14:35 Ready for new connections
Step #1 - "migrate": 2023/06/05 15:14:35 Generated RSA key in 64.995929ms
Step #1 - "migrate": System check identified some issues:
Step #1 - "migrate": 
Step #1 - "migrate": WARNINGS:
Step #1 - "migrate": ?: (wagtailadmin.W004) The GS_FILE_OVERWRITE setting is set to True
Step #1 - "migrate":    HINT: This should be set to False. The incorrect setting can cause documents and other user-uploaded files to be silently overwritten or deleted.
Step #1 - "migrate": 2023/06/05 15:14:40 New connection for "phx-01h1yptgmche7jcy01wzzpw2rf:us-central1:myinstance"
Step #1 - "migrate": 2023/06/05 15:14:40 refreshing ephemeral certificate for instance phx-01h1yptgmche7jcy01wzzpw2rf:us-central1:myinstance
Step #1 - "migrate": 2023/06/05 15:14:40 Scheduling refresh of ephemeral certificate in 55m0s
Step #1 - "migrate": Operations to perform:
Step #1 - "migrate":   Apply all migrations: admin, auth, contenttypes, home, myproject, sessions, taggit, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailredirects, wagtailsearch, wagtailusers
Step #1 - "migrate": Running migrations:
Step #1 - "migrate":   No migrations to apply.
Step #1 - "migrate": 2023/06/05 15:14:43 Client closed local connection on 127.0.0.1:5432
Step #1 - "migrate": Traceback (most recent call last):
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2540, in upload_from_file
Step #1 - "migrate":     created_json = self._do_upload(
Step #1 - "migrate":                    ^^^^^^^^^^^^^^^^
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2355, in _do_upload
Step #1 - "migrate":     response = self._do_multipart_upload(
Step #1 - "migrate":                ^^^^^^^^^^^^^^^^^^^^^^^^^^
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 1890, in _do_multipart_upload
Step #1 - "migrate":     response = upload.transmit(
Step #1 - "migrate":                ^^^^^^^^^^^^^^^^
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/resumable_media/requests/upload.py", line 153, in transmit
Step #1 - "migrate":     return _request_helpers.wait_and_retry(
Step #1 - "migrate":            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
Step #1 - "migrate":     response = func()
Step #1 - "migrate":                ^^^^^^
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/resumable_media/requests/upload.py", line 149, in retriable_request
Step #1 - "migrate":     self._process_response(result)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/resumable_media/_upload.py", line 114, in _process_response
Step #1 - "migrate":     _helpers.require_status_code(response, (http.client.OK,), self._get_status_code)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
Step #1 - "migrate":     raise common.InvalidResponse(
Step #1 - "migrate": google.resumable_media.common.InvalidResponse: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>)
Step #1 - "migrate": 
Step #1 - "migrate": During handling of the above exception, another exception occurred:
Step #1 - "migrate": 
Step #1 - "migrate": Traceback (most recent call last):
Step #1 - "migrate":   File "/workspace/manage.py", line 10, in <module>
Step #1 - "migrate":     execute_from_command_line(sys.argv)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
Step #1 - "migrate":     utility.execute()
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
Step #1 - "migrate":     self.fetch_command(subcommand).run_from_argv(self.argv)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
Step #1 - "migrate":     self.execute(*args, **cmd_options)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
Step #1 - "migrate":     output = self.handle(*args, **options)
Step #1 - "migrate":              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
Step #1 - "migrate":     collected = self.collect()
Step #1 - "migrate":                 ^^^^^^^^^^^^^^
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 135, in collect
Step #1 - "migrate":     handler(path, prefixed_path, storage)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 378, in copy_file
Step #1 - "migrate":     self.storage.save(prefixed_path, source_file)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/django/core/files/storage/base.py", line 38, in save
Step #1 - "migrate":     name = self._save(name, content)
Step #1 - "migrate":            ^^^^^^^^^^^^^^^^^^^^^^^^^
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/storages/backends/gcloud.py", line 174, in _save
Step #1 - "migrate":     file_object.blob.upload_from_file(content, rewind=True, size=content.size, **upload_params)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2557, in upload_from_file
Step #1 - "migrate":     _raise_from_invalid_response(exc)
Step #1 - "migrate":   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 4369, in _raise_from_invalid_response
Step #1 - "migrate":     raise exceptions.from_http_status(response.status_code, message, response=response)
Step #1 - "migrate": google.api_core.exceptions.BadRequest: 400 POST https://storage.googleapis.com/upload/storage/v1/b/phx-01h1yptgmche7jcy01wzzpw2rf-media/o?uploadType=multipart&predefinedAcl=publicRead: {
Step #1 - "migrate":   "error": {
Step #1 - "migrate":     "code": 400,
Step #1 - "migrate":     "message": "Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access",
Step #1 - "migrate":     "errors": [
Step #1 - "migrate":       {
Step #1 - "migrate":         "message": "Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access",
Step #1 - "migrate":         "domain": "global",
Step #1 - "migrate":         "reason": "invalid"
Step #1 - "migrate":       }
Step #1 - "migrate":     ]
Step #1 - "migrate":   }
Step #1 - "migrate": }
Step #1 - "migrate": : ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>)
Finished Step #1 - "migrate"
ERROR
ERROR: build step 1 "gcr.io/phx-01h1yptgmche7jcy01wzzpw2rf/myimage-proxy" failed: step exited with non-zero status: 1
```

**Comment by glasnt** [comment]
The bucket should have been created with fine-grained access by default.

Check if your media bucket is actually set to uniform level access: 

```
gsutil uniformbucketlevelaccess get gs://${PROJECT_ID}-media
```

If you get `Enabled: True`, then you'll need to change the setting: 

```
gsutil uniformbucketlevelaccess set off gs://${PROJECT_ID}-media
```

Then try your migration again. 

More information: 

 * https://cloud.google.com/storage/docs/using-uniform-bucket-level-access
 * https://django-storages.readthedocs.io/en/latest/backends/gcloud.html#gs-default-acl

**Comment by KingBain** [comment]
Thanks @glasnt 

![image](https://github.com/googlecodelabs/feedback/assets/367922/d913e1af-5f86-4ef9-b0e7-ca48b68331be)

that was it. My GCP org administrator has a policy enforcing Uniform bucket-level access. Will have to look at what a work around could be, as I cant disable the policy.

**Comment by KingBain** [comment]
just keeping my notes to push through this issue. 
![image](https://github.com/googlecodelabs/feedback/assets/367922/45c8b275-fa03-489d-9717-f2d0e92020a7)

https://django-storages.readthedocs.io/en/latest/backends/gcloud.html

changes need to be made to the settings.py file in the tutorial

**Comment by KingBain** [comment]
Needed to also define regions when creating secrets. 

gcloud secrets create admin_password --locations=$REGION --replication-policy=user-managed --data-file=-

**Comment by KingBain** [comment]
:(, doesnt like GS_DEFAULT_ACL being set to "none" 
![image](https://github.com/googlecodelabs/feedback/assets/367922/cd652b2a-281c-47e0-b386-cba855db0986)

**Comment by glasnt** [comment]
These codelabs presuppose that you are not limited by organisation policies. Debugging specific org policy limits is outside the support that we can offer. 

I would try not setting GS_DEFAULT_ACL at all, see if that helps. 

That error is coming from google-cloud-storage, where it expects a known list https://github.com/googleapis/python-storage/blob/main/google/cloud/storage/acl.py#L121, so having the failure on `None` may be a bug in django-storages.
