### ISSUE TITLE
auth not working?

### ISSUE THREAD

**Issue by moses5407** [googlecodelabs/feedback#153]
no popup comes up when clicking sign in with Google?The interface elements work normally and I've double-checked code against the example code.

The only difference is my database is named todo .. but I edited the firebase-auth appname to "todo".

Is there something else I should look for? Any change since the tutorial was published?

**Comment by moses5407** [comment]
Forgot to mention I'm in Chromium ..  and I have hard-refreshed to dump the cache.

**Comment by moses5407** [comment]
teh console shows this:
Uncaught TypeError: Cannot read property 'signInWithPopup' of undefined
    at HTMLElement.signInWithPopup (VM128 firebase-auth.html:184)
    at HTMLElement.signIn (VM136 note-app.html:42)
    at HTMLElement.handler (VM87 polymer.html:566)
    at HTMLElement.fire (VM87 polymer.html:1343)
    at HTMLElement.signIn (VM115 na-login.html:66)
    at HTMLElement.handler (VM87 polymer.html:566)
    at HTMLElement.fire (VM87 polymer.html:1343)
    at Object.fire (VM87 polymer.html:915)
    at Object.forward (VM87 polymer.html:1212)
    at Object.click (VM87 polymer.html:1197)

Looks like maybe a code change?

**Comment by curtisolson** [comment]
I'm also having this problem and agree that it looks like a code change with sw-toolbox. https://github.com/GoogleChrome/sw-toolbox

I'm seeing sw-toolbox-setup.js trying to include sw-toolbox.js and that files doesn't exist. From the source project, there was a commit that looks like it added sw-toolbox.js to it's .gitignore. I tried to use an older version of sw-toolbox.js but just ran in circle because I don't understand the dependencies well enough.

`sw-toolbox-setup.js:13 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:5000/bower_components/sw-toolbox/sw-toolbox.js' failed to load.
    at http://localhost:5000/bower_components/platinum-sw/bootstrap/sw-toolbox-setup.js:13:3
    at http://localhost:5000/bower_components/platinum-sw/bootstrap/sw-toolbox-setup.js:63:3
    at http://localhost:5000/bower_components/platinum-sw/service-worker.js:39:7
    at http://localhost:5000/bower_components/platinum-sw/service-worker.js:54:3
    at http://localhost:5000/sw-import.js?baseURI=http%3A%2F%2Flocalhost%3A5000%2F…bootstrap%2Fsw-toolbox-setup.js&precache=&skipWaiting=true&version=1.0:1:1`

**Comment by curtisolson** [comment]
FWIW, it's not the auth part that isn't working, it is the service worker code that is broken. I was able to get the demo app to work by leaving those parts out. 

Those includes steps are:

5: Don't bother to create sw-imports.js file.
8: All of it.
10: Leave out the 3rd line of the code.
`<link rel="import" href="bower_components/platinum-sw/platinum-sw-elements.html">`
11: All of it.
27: The 2nd part of that step: **Disabling edit when offline**

You can check out my version here. [https://polymer-demo-1f64f.firebaseapp.com/](https://polymer-demo-1f64f.firebaseapp.com/)

Step 27 "Add to Homescreen" works, but the app icon is a grey F instead of what the instruction show. I think there is some dependency on the server worker code for this.

**Comment by moses5407** [comment]
Thanks for that info!

**Comment by ghost** [comment]
Could you please give us a link to a GitHub repository where we can take a better look at your version? I'm sure a lot of us (including me) have this problem.

**Comment by thyeun** [comment]
i have the same issue also 

![selection_001](https://user-images.githubusercontent.com/1939446/35427790-787d5e1e-02a6-11e8-81f6-054f5883bfcc.png)
