### ISSUE TITLE
22: Implement a signing listener

### ISSUE THREAD

**Issue by basiccreation** [googlecodelabs/feedback#156]
Because I had typed something wrong, I decided to start over, however I copied and pasted everything up until this chapter where I discovered my error previously. 

Anyways. I can't log in nor out or go off line as shown in the chapter. Below are the error messages from console.

Do I need to update something since it can't. find certain things?

thanks,
Pia

sw-import.js?baseURI=http%3A%2F%2Flocalhost%3A5000%2Fbower_components%2Fplatinum-sw%2Fplatinum-sw-r…:1 A bad HTTP response code (404) was received when fetching the script.
http://localhost:5000/bower_components/sw-toolbox/sw-toolbox.js Failed to load resource: net::ERR_INVALID_RESPONSE
sw-toolbox-setup.js:13 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:5000/bower_components/sw-toolbox/sw-toolbox.js' failed to load.
    at http://localhost:5000/bower_components/platinum-sw/bootstrap/sw-toolbox-setup.js:13:3
    at http://localhost:5000/bower_components/platinum-sw/bootstrap/sw-toolbox-setup.js:63:3
    at http://localhost:5000/bower_components/platinum-sw/service-worker.js:39:7
    at http://localhost:5000/bower_components/platinum-sw/service-worker.js:54:3
    at http://localhost:5000/sw-import.js?baseURI=http%3A%2F%2Flocalhost%3A5000%2F…bootstrap%2Fsw-toolbox-setup.js&precache=&skipWaiting=true&version=1.0:1:1

**Comment by x1ddos** [comment]
@basiccreation sorry, which codelab is it? could you post a link to the page.
