### ISSUE TITLE
[cloud-tensorflow-mnist]: Install test gives AttributeError

### ISSUE THREAD

**Issue by tosandip** [googlecodelabs/feedback#165]
Following the instructions on

https://github.com/martin-gorner/tensorflow-mnist-tutorial/blob/master/INSTALL.txt

I get the following error:

~/tensorflow-mnist-tutorial$ python3 mnist_1.0_softmax.py
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "mnist_1.0_softmax.py", line 80, in <module>
    datavis = tensorflowvisu.MnistDataVis()
  File "/home/sandip/tensorflow-mnist-tutorial/tensorflowvisu.py", line 166, in __init__
    self._color4 = self.__get_histogram_cyclecolor(histogram4colornum)
  File "/home/sandip/tensorflow-mnist-tutorial/tensorflowvisu.py", line 160, in __get_histogram_cyclecolor
    colors = clist.by_key()['color']
AttributeError: 'Cycler' object has no attribute 'by_key'

**Comment by orbitmoon** [comment]
I have fixed this by upgrade my matplotlib by pip install --upgrade matplotlib(using python2.7).
And you can solve this problem by some hardcoding.(not suggest)
details in :https://github.com/martin-gorner/tensorflow-mnist-tutorial/issues/10
I find it very helpful.

**Comment by richardjgo** [comment]
`conda list `gives me two versions of matplotlib (1.5 and 2.0) to use the latest ver is automatic in python? thx
