### ISSUE TITLE
[tensorflow-mnist-tutorial ]  mnist_1.0_softmax.py   attribute error 'Cycler' in visu

### ISSUE THREAD

**Issue by richardjgo** [googlecodelabs/feedback#230]
laptop:tensorflow-mnist-tutorial user$ python mnist_1.0_softmax.py 
Tensorflow version 1.1.0
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "mnist_1.0_softmax.py", line 81, in <module>
    datavis = tensorflowvisu.MnistDataVis()
  File "/Users/user/tensorflow-mnist-tutorial/tensorflowvisu.py", line 166, in __init__
    self._color4 = self.__get_histogram_cyclecolor(histogram4colornum)
  File "/Users/user/tensorflow-mnist-tutorial/tensorflowvisu.py", line 160, in __get_histogram_cyclecolor
    colors = clist.by_key()['color']
AttributeError: 'Cycler' object has no attribute 'by_key'

**Comment by richardjgo** [comment]
workaround by updating to matplotlib 2.0, and running thru pythonw within conda environment
