### ISSUE TITLE
[cloud-create-a-vm]:

### ISSUE THREAD

**Issue by richprze** [googlecodelabs/feedback#302]
In step 5 - install Node.js. Starting the node js app throws the below error. Looks like a server is already running on this port? 

`Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at EventEmitter.listen (/home/richprze/nodejs-docs-samples/appengine/hello-world/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/richprze/nodejs-docs-samples/appengine/hello-world/app.js:29:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
`

**Comment by alexismp** [comment]
A newly-created GCE instance does not have anything running...
