### ISSUE TITLE
[cloud-slack-bot]: Old version of Botkit npm

### ISSUE THREAD

**Issue by sfkrieger** [googlecodelabs/feedback#423]
I saw this repo is 2 years out of date. I believe that Botkit may have made some changes, it is now up to version 0.6.14 - https://www.npmjs.com/package/botkit

Was getting the following error trace when running step 6. Bot still responds, this error is not terminal.

```
info: ** API CALL: https://slack.com/api/rtm.start
Error in Botkit Studio Stats: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/home/cloud-slack-bot/start/node_modules/botkit/lib/Studio.js:459:33)
    at Request.self.callback (/home/cloud-slack-bot/start/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/cloud-slack-bot/start/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/cloud-slack-bot/start/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
debug: Got response null 
```

**Comment by tswast** [comment]
Thanks for the report. I started on this at https://github.com/googlecodelabs/cloud-slack-bot/pull/7 but the tutorial needs an update to use Client ID & Secrets instead of tokens.

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
