### ISSUE TITLE
[cloud-mongodb-statefulset]: MongoDB binds to localhost by default

### ISSUE THREAD

**Issue by areller** [googlecodelabs/feedback#435]
You have to explicitly specify bind_ip, otherwise mongodb will bind to localhost and won't be able to communicate with other nodes and create a replica set

<img width="211" alt="screen shot 2018-06-08 at 13 25 53" src="https://user-images.githubusercontent.com/15989650/41171710-878076d0-6b1f-11e8-87a4-2a54e6b8d8be.png">

**Comment by stigok** [comment]
That sure took a while for me to figure out too. The [upstream example files](https://github.com/cvallance/mongo-k8s-sidecar/blob/master/example/StatefulSet/mongo-statefulset.yaml) specifies `--bind_ip` correctly.

When it binds to localhost, you will get seemingly healthy pods while the sidecar goes in an error loop
```
Error in workloop { MongoError: failed to connect to server [10.244.0.67:27017] on first connect [MongoError: connect ECONNREFUSED 10.244.0.67:27017]
    at Pool.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:180:13)
    at Connection.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Socket.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
  name: 'MongoError',
  message: 'failed to connect to server [10.244.0.67:27017] on first connect [MongoError: connect ECONNREFUSED 10.244.0.67:27017]' }
```

**Comment by areller** [comment]
@stigok In that case the actual code lab (as seen in the attached screenshot) is inconsistent with the upstream example files that you've mentioned because in the code lab itself they don't specify a bind-ip argument so it automatically binds to localhost.

<img width="1186" alt="screen shot 2018-07-02 at 12 00 20" src="https://user-images.githubusercontent.com/15989650/42174232-9790768c-7def-11e8-9eed-7515c210f3f8.png">
