### ISSUE TITLE
[cloud-create-a-vm]:

### ISSUE THREAD

**Issue by jpanged** [googlecodelabs/feedback#447]
I get the following error when trying to npm start the program

> appengine-hello-world@0.0.1 start /home/pang_josiah/nodejs-docs-samples/appengine/hello-world/flexible
> node app.js
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::80
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at Function.listen (/home/pang_josiah/nodejs-docs-samples/appengine/hello-world/flexible/node_modules/express/lib/appl
ication.js:618:24)
    at Object.<anonymous> (/home/pang_josiah/nodejs-docs-samples/appengine/hello-world/flexible/app.js:29:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appengine-hello-world@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appengine-hello-world@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-15T17_18_55_107Z-debug.log

**Comment by alexismp** [comment]
Thanks for the report.
I have updated the instructions to use nodejs-docs-samples/appengine/hello-world/standard which should fix your issue. Please reopen if it didn't.
