### ISSUE TITLE
[cloud-speech-nodejs]: broken example

### ISSUE THREAD

**Issue by delip** [googlecodelabs/feedback#455]
I followed this example. 
https://codelabs.developers.google.com/codelabs/cloud-speech-nodejs/index.html?index=..%2F..%2Findex#2
It breaks with the following error:

```
node recognize --help
module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/delip/gctest/nodejs-docs-samples/recognize'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by danielnascgomes** [comment]
Also need to know the solution for this problem.
