### ISSUE TITLE
[cloud-slack-bot]: node version in Dockerfile is out of date

### ISSUE THREAD

**Issue by ldeza** [googlecodelabs/feedback#560]
The node version in Dockerfile (5.4) is out of date. The generated docker image does not start correctly. Looking at the docker logs indicates a SyntaxError with this version of node.

```
$ docker logs  16c2226408d8
/src/node_modules/botkit/lib/SlackBot.js:235
            let timestamp = req.header('X-Slack-Request-Timestamp');
            ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/src/node_modules/botkit/lib/Botkit.js:2:16)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
```

Upgrading the version of node to the same version as cloudshell and rebuilding the image fixes the issue.

```
$ node --version
v10.14.2
```

New Dockerfile

```
FROM node:10.14.2
COPY package.json /src/package.json
WORKDIR /src
RUN npm install
COPY kittenbot.js /src
CMD ["node", "/src/kittenbot.js"]
```

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
