### ISSUE TITLE
[cloud-tensorflow-mnist]:

### ISSUE THREAD

**Issue by dturvene** [googlecodelabs/feedback#598]
My system:
```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
> python3 --version
Python 3.6.7
```

I did the steps in *INSTALL.txt*.  First run caused a fault:

```
> python3 mnist_1.0_softmax.py
INFO:tensorflow:Tensorflow version 1.13.1
Tensorflow version 1.13.1
2019-06-10 12:14:10.129553: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-10 12:14:10.149890: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2208000000 Hz
2019-06-10 12:14:10.151165: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x1a326e0 executing computations on platform Host. Devices:
2019-06-10 12:14:10.151214: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "mnist_1.0_softmax.py", line 82, in <module>
    datavis = tensorflowvisu.MnistDataVis()
  File "/opt/distros/tensorflow-without-a-phd/tensorflow-mnist-tutorial/tensorflowvisu.py", line 192, in __init__
    legend.draggable(True)
AttributeError: 'Legend' object has no attribute 'draggable'
```
Fixed by removing legend.draggable call and visual runs:

```
> git diff
diff --git a/tensorflow-mnist-tutorial/tensorflowvisu.py b/tensorflow-mnist-tutorial/tensorflowvisu.py
index bc27ef9..14cc52f 100644
--- a/tensorflow-mnist-tutorial/tensorflowvisu.py
+++ b/tensorflow-mnist-tutorial/tensorflowvisu.py
@@ -189,12 +189,12 @@ class MnistDataVis:
         line1, = ax1.plot(self.x1, self.y1, label="training accuracy")
         line2, = ax1.plot(self.x2, self.y2, label="test accuracy")
         legend = ax1.legend(loc='lower right') # fancybox : slightly rounded corners
-        legend.draggable(True)
+        #legend.draggable(True)
 
         line3, = ax2.plot(self.x1, self.z1, label="training loss")
         line4, = ax2.plot(self.x2, self.z2, label="test loss")
         legend = ax2.legend(loc='upper right') # fancybox : slightly rounded corners
-        legend.draggable(True)
+        #legend.draggable(True)
 
         ax3.grid(False) # toggle grid off
         ax3.set_axis_off()
```

**Comment by martin-gorner** [comment]
Thank you for your feedback. The entire lab was revamped for modern Tensorflow and now uses Keras as its high-level API and runs entirely in Colaboratory. No more installs.
