### ISSUE TITLE
[cloud-slack-bot]:

### ISSUE THREAD

**Issue by nitesh1306** [googlecodelabs/feedback#599]
I am getting below error when i run the docker image in step 8.

/src/node_modules/botkit/lib/SlackBot.js:235
            let timestamp = req.header('X-Slack-Request-Timestamp');
            ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/src/node_modules/botkit/lib/Botkit.js:2:16)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
