### ISSUE TITLE
[cloud-run-django]: Step 8 fails

### ISSUE THREAD

**Issue by hohaichi** [googlecodelabs/feedback#863]
```
gcloud builds submit --config cloudmigrate.yaml \
    --substitutions _REGION=$REGION
```
fails with `django.db.utils.OperationalError: fe_sendauth: no password supplied`.

Below is the full stack trace:
```
Step #2: ---------- EXECUTE COMMAND ----------
Step #2: python manage.py migrate
Step #2: Traceback (most recent call last):
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
Step #2:     self.connect()
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
Step #2:     return func(*args, **kwargs)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
Step #2:     self.connection = self.get_new_connection(conn_params)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
Step #2:     return func(*args, **kwargs)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
Step #2:     connection = Database.connect(**conn_params)
Step #2:   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
Step #2:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Step #2: psycopg2.OperationalError: fe_sendauth: no password supplied
Step #2:
Step #2:
Step #2: The above exception was the direct cause of the following exception:
Step #2:
Step #2: Traceback (most recent call last):
Step #2:   File "manage.py", line 22, in <module>
Step #2:     main()
Step #2:   File "manage.py", line 18, in main
Step #2:     execute_from_command_line(sys.argv)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
Step #2:     utility.execute()
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
Step #2:     self.fetch_command(subcommand).run_from_argv(self.argv)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
Step #2:     self.execute(*args, **cmd_options)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
Step #2:     output = self.handle(*args, **options)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
Step #2:     res = handle_func(*args, **kwargs)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 92, in handle
Step #2:     executor = MigrationExecutor(connection, self.migration_progress_callback)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
Step #2:     self.loader = MigrationLoader(self.connection)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__
Step #2:     self.build_graph()
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 216, in build_graph
Step #2:     self.applied_migrations = recorder.applied_migrations()
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
Step #2:     if self.has_table():
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table
Step #2:     with self.connection.cursor() as cursor:
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
Step #2:     return func(*args, **kwargs)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
Step #2:     return self._cursor()
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
Step #2:     self.ensure_connection()
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
Step #2:     return func(*args, **kwargs)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
Step #2:     self.connect()
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
Step #2:     raise dj_exc_value.with_traceback(traceback) from exc_value
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
Step #2:     self.connect()
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
Step #2:     return func(*args, **kwargs)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
Step #2:     self.connection = self.get_new_connection(conn_params)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
Step #2:     return func(*args, **kwargs)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
Step #2:     connection = Database.connect(**conn_params)
Step #2:   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
Step #2:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Step #2: django.db.utils.OperationalError: fe_sendauth: no password supplied
Step #2:
Finished Step #2
ERROR
ERROR: build step 2 "gcr.io/google-appengine/exec-wrapper" failed: step exited with non-zero status: 1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ERROR: (gcloud.builds.submit) build 844971de-6268-4035-b460-95c15eb66be6 completed with status "FAILURE"
```

**Comment by hohaichi** [comment]
I figured out what's wrong.  $DJPASS got lost when I lost the connection to CloudShell, resulting in an empty password in the secret manager.

To check: view the secret in secret manager (see the empty password after djuser):
DATABASE_URL="postgres://djuser:@//cloudsql/cloud-run-learning-1:us-west1:myinstance/mydatabase"

To fix: regenerate password, update the secret, and update the password of djuser in SQL.
