### ISSUE TITLE
[fido2-for-android]: Sample APK provided keeps on loading and then crashes

### ISSUE THREAD

**Issue by adityasinha26** [googlecodelabs/feedback#911]
"https://webauthn-codelab.glitch.me" mentioned in the codelab also gives http code 504 Gateway Timeout error.

Kindly help. Below is the stack trace.

```
02-17 09:58:58.195 15451 15512 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
02-17 09:58:58.195 15451 15512 E AndroidRuntime: Process: com.example.android.fido2, PID: 15451
02-17 09:58:58.195 15451 15512 E AndroidRuntime: java.lang.Error: java.net.SocketTimeoutException: timeout
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: Caused by: java.net.SocketTimeoutException: timeout
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at com.example.android.fido2.api.AddHeaderInterceptor.intercept(AddHeaderInterceptor.kt:24)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at okhttp3.RealCall.execute(RealCall.java:93)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at com.example.android.fido2.api.AuthApi.username(AuthApi.kt:76)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at com.example.android.fido2.repository.AuthRepository$username$1.run(AuthRepository.kt:133)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-17 09:58:58.195 15451 15512 E AndroidRuntime: 	... 2 more
02-17 10:09:18.657 15441 17707 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
02-17 10:09:18.657 15441 17707 E AndroidRuntime: Process: com.example.android.fido2, PID: 15441
02-17 10:09:18.657 15441 17707 E AndroidRuntime: java.lang.Error: java.net.SocketTimeoutException: timeout
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: Caused by: java.net.SocketTimeoutException: timeout
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at com.example.android.fido2.api.AddHeaderInterceptor.intercept(AddHeaderInterceptor.kt:24)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at okhttp3.RealCall.execute(RealCall.java:93)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at com.example.android.fido2.api.AuthApi.username(AuthApi.kt:76)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at com.example.android.fido2.repository.AuthRepository$username$1.run(AuthRepository.kt:133)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-17 10:09:18.657 15441 17707 E AndroidRuntime: 	... 2 more
```

**Comment by adityasinha26** [comment]
![Screenshot 2021-02-17 at 10 29 31 AM](https://user-images.githubusercontent.com/48233270/108158504-107ae300-710b-11eb-9291-1e721b87fddd.png)

Getting this on https://webauthn-codelab.glitch.me

**Comment by adityasinha26** [comment]
Working with sample codelab in webauthn...Closing this
